// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import { loadMorphoCode } from '../js/utils.js';
import { parse } from '../js/parser.js';
import { compileModule, CELL_TYPES } from '../js/compiler.js';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { exec } from 'child_process';
import { promisify } from 'util';

const execPromise = promisify(exec);

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const workspaceRoot = path.resolve(__dirname, '..');

async function main() {
    const rootName = 'wallace_multiplier';
    const rootInputSignature = [16, 16];

    try {
        const code = await loadMorphoCode(workspaceRoot);
        const parsed = parse(code);
        const { registry } = compileModule(parsed, rootName, rootInputSignature);
        
        const rootKey = `${rootName}:[${rootInputSignature.join(',')}]`;
        
        // Generate Module Table
        let tableRows = "";
        for (const [key, graph] of registry.entries()) {
            if (!graph) continue;
            const inputs = graph.inputNames.map((name, i) => `${name}[${graph.inputSignature[i]}]`).join(', ');
            const outputs = graph.outputNames.map((name, i) => `${name}[${graph.outputSignature[i]}]`).join(', ');
            const lutCount = graph.estimateLUTCount || 0;
            tableRows += `| \`${key}\` | ${inputs} | ${outputs} | ${lutCount} |\n`;
        }

        const now = new Date().toISOString().replace('T', ' ').substring(0, 19);

        // Assemble markdown content
        const markdownContent = `# Morpho Module Dependency Analysis: Wallace Multiplier (16x16)

This document provides a visualization and structural inventory of the compiled hardware modules and their dependencies, generated by the Morpho HDL synthesis compiler for \`${rootKey}\`.

## Dependency Diagram

Below is the hierarchical dependency graph showing the relationship between modules in the compilation registry.

![Recursive Carry-Save Multiplier](../data/wallace_dependencies.svg)

## Module Inventory & Metrics

The table below lists all modules registered during compilation, showing their signature parameters, input/output structures, and estimated LUT resources:

| Module Key | Inputs | Outputs | Est. LUTs |
| :--- | :--- | :--- | :---: |
${tableRows}
---
*Generated automatically on ${now} UTC by the Morpho Compile CLI.*
`;

        const outputFilePath = path.resolve(workspaceRoot, 'scratch', 'wallace_dependencies.md');
        await fs.writeFile(outputFilePath, markdownContent, 'utf8');
        console.log(`Successfully generated dependency report at: ${outputFilePath}`);

        // Generate Graphviz DOT representation
        let dot = 'digraph G {\n';
        dot += '  bgcolor="#0b0f19";\n';
        dot += '  pad="0.5";\n';
        dot += '  nodesep="0.6";\n';
        dot += '  ranksep="0.5";\n';
        dot += '  node [\n';
        dot += '    shape=box,\n';
        dot += '    style="filled,rounded",\n';
        dot += '    fontname="system-ui, -apple-system, sans-serif",\n';
        dot += '    fontsize=14,\n';
        dot += '    fillcolor="#1e293b",\n';
        dot += '    color="#666",\n';
        dot += '    fontcolor="#cbd5e1",\n';
        dot += '    penwidth=1\n';
        dot += '  ];\n';
        dot += '  edge [\n';
        dot += '    color="#667",\n';
        dot += '    arrowhead=vee,\n';
        dot += '    arrowsize=0.8,\n';
        dot += '    penwidth=1.2\n';
        dot += '  ];\n\n';

        for (const [key, graph] of registry.entries()) {
            if (!graph) continue;
            const isRoot = key === rootKey;
            const isBase = key.includes('base') || key.startsWith('full_adder');
            
            const splitIdx = key.indexOf(':[');
            let label = key;
            if (splitIdx !== -1) {
                label = `${key.substring(0, splitIdx)}\\n${key.substring(splitIdx + 1)}`;
            }

            let attrsList = [`label="${label}"`];
            if (isRoot) {
                attrsList.push('fillcolor="#065f46"', 'color="#34d399"', 'fontcolor="#f0fdf4"', 'penwidth=2', 'style="filled,rounded,bold"');
            } else if (!isBase) {
                attrsList.push('fillcolor="#111827"', 'color="#374151"', 'fontcolor="#f3f4f6"');
            }
            dot += `  "${key}" [${attrsList.join(', ')}];\n`;
        }
        dot += '\n';

        const dotEdgeSet = new Set();
        for (const [key, graph] of registry.entries()) {
            if (!graph) continue;
            for (let i = 0; i < graph.cell.count; i++) {
                if (graph.cell.active[i] === 1 && graph.cell.type[i] === CELL_TYPES.MORPHO) {
                    const depKey = graph.cell.name[i];
                    const edgeStr = `  "${key}" -> "${depKey}";\n`;
                    if (!dotEdgeSet.has(edgeStr)) {
                        dotEdgeSet.add(edgeStr);
                        dot += edgeStr;
                    }
                }
            }
        }
        dot += '}\n';

        const dotFilePath = path.resolve(workspaceRoot, 'data', 'wallace_dependencies.dot');
        await fs.writeFile(dotFilePath, dot, 'utf8');
        console.log(`Successfully generated DOT representation at: ${dotFilePath}`);

        const svgOutputPath = path.resolve(workspaceRoot, 'data', 'wallace_dependencies.svg');
        await execPromise(`dot -Tsvg "${dotFilePath}" -o "${svgOutputPath}"`);
        console.log(`Successfully rendered SVG using Graphviz dot at: ${svgOutputPath}`);

    } catch (e) {
        console.error("Compilation / Generation failed:", e);
    }
}

main();
